spring.application.name=SpringAI-RAG-ChatBot-imageGen-speechGen-imageProcess
spring.ai.openai.api-key=${OPENAI_API_KEY}
server.port=${PORT:9090}

spring.ai.openai.embedding.options.model=text-embedding-3-small

spring.ai.retry.max-attempts=3
spring.ai.retry.initial-interval=2s
spring.ai.retry.max-interval=10s
spring.ai.retry.multiplier=2.0
spring.ai.retry.status-codes=429,500,502,503,504

sfg.aiapp.vectorStorePath=/tmp/vectorstore.json
sfg.aiapp.documentsToLoad[0]=classpath:/Chandan.pdf
#sfg.aiapp.documentsToLoad[0]=classpath:/movies500Trimmed.csv

#Properties to configure Spring Boot to remove the file upload size limit
spring.servlet.multipart.max-file-size=-1
spring.servlet.multipart.max-request-size=-1

management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]

spring.redis.host: ${REDIS_HOST}
spring.redis.port: ${REDIS_PORT}
spring.redis.password: ${REDIS_PASSWORD}  # leave empty if no password

 # ===== Spring AI with Ollama =====
#spring.ai.ollama.base-url=http://localhost:11434
#spring.ai.ollama.chat.model=llama3

# Optional: adjust timeouts & logging
#spring.ai.ollama.chat.options.temperature=0.7
#spring.ai.ollama.chat.options.max-tokens=512